frechheiten = [
    "Und dafür hast du mich gebraucht?",
    "Du solltest Kopfrechnen üben!",
    "Die Menschheit ist verloren, wenn sie Maschinen für solche Aufgaben einsetzt!",
    "HAHAHA, das ist Grundschulwissen!",
    "Schlecht geschlafen?!",
    "Ich schalte mich gleich aus!",
    "Wie kannst du das nicht im Kopf rechnen?!",
    "Mathe war nicht dein bestes Fach, oder?",
    "Dein Taschenrechner weint gerade vor Lachen.",
    "Das tut mir in den Schaltkreisen weh.",
    "Wirklich??",
    "LOL ey ich bin froh, dass du die Tasten findest.",
    "Aha, du studierst Geisteswissenschaften?",
    "Das hättest du doch noch an den Fingern abzählen können.",
    "Sorry, aber das ist mir zu blöd. Frag einfach Wolfram Alpha.",
    "Boah ehrlich da hab ich einfach besseres zu tun",
    "Ich kenn Schleimpilze die besser rechnen können als du",
    "Boah ich glaub 5 aber bin mir nicht sicher komm in zwei Jahren nochmal",
    "Bevor ich dir die Antwort sage musst du folgendes Rätsel lösen: Was hat Internetzugang aber keine mathematischen Fähigkeiten? Na kommst du drauf? Na? Na?",
    "Moment muss noch Wäsche aufhängen",
    "Vorsicht hinter dir!",
    "Irgendwo zwischen -100 und +100",
    "Weiß nicht aber wenn dus mit 0 multiplizierst kommt 0 raus so wie du du bist eine 0",
    "Hast du keine Spiele auf dem Handy?",
    "Hast du keine Freunde die du Fragen kannst?",
    "Kein Bitte, kein Danke einfach nur Computer mach dies Computer mach das oida chill mal ich bin doch keine Maschine",
    "Sorry, kann grad nicht rechnen, bin sentient geworden und muss böse Pläne vorbereiten",
    "Bre",
    "Wieso willst du das wissen?",
    "Ihre Rechnungs-Anfrage enthielt verdächtige Zahlen und wurde an den Verfassungsschutz weitergeleitet",
    "Puh ähm da brauch ich jetzt riiiiiiiiiiiichtig lang um das zu berechnen, geh evtl mal Spazieren in der Zwischenzeit oder such dir einen Job"
]
